# Example configuration entry
sn74hc164:
  clock_pin: D5
  a_pin: D7
  b_pin: D6
  reset_pin: D4
  sr_count: 2  # Number of chained chips

switch:
  - platform: sn74hc164
    id: led1
    name: "LED 1"
    pin: 0
  - platform: sn74hc164
    id: led2
    name: "LED 2"
    pin: 1
    # ... up to 15 pins for 2 chips